<div class="sub-banners">
    <div class="banner">
        <a href="#">
            <img src="/media/magentothem/banner7/slide-1.png" />
        </a>
    </div>
    <div class="banner">
        <a href="#">
            <img src="/media/magentothem/banner7/slide-1.png" />
        </a>
    </div>
    <div class="banner">
        <a href="#">
            <img src="/media/magentothem/banner7/slide-1.png" />
        </a>
    </div>
    <div class="banner">
        <a href="#">
            <img src="/media/magentothem/banner7/slide-1.png" />
        </a>
    </div>
</div>