<script type="text/javascript">
    $jq(document).ready(function(){
         var enable_module = $jq('#enable_module').val();
         if(enable_module==0) return false;
    })

</script>
<?php $_cartQty = $this->getSummaryCount() ?>
<div id ="mini_cart_block">
    <div class="block-cart mini_cart_ajax">
            <div class="block-cart">
                <?php $_cartQty = $this->getSummaryCount() ?>
                <span class="top-cart-title"></span>
                <?php if ($_cartQty>0): ?>
                        <?php if ($_cartQty==1): ?>
                            <?php echo $this->__('<a href="%s"><span class="top-cart-price">1 - </span><span>Item</span></a>', $this->getUrl('checkout/cart')) ?>
                        <?php else: ?>
                            <?php echo $this->__('<a href="%s"><span class="top-cart-price">%s - </span><span>Items</span></a>', $this->getUrl('checkout/cart'), $_cartQty) ?>
                        <?php endif ?>
                <?php endif ?>
                
                <?php $_items = $this->getRecentItems() ?>
                <?php if(count($_items)): ?>
                <?php else: ?>
                    <span class="top-cart-price"><?php echo $this->__('0 - </span><span>Item') ?></span>
                <?php endif ?>
                <div class="top-cart-content">
                    <?php $_items = $this->getRecentItems() ?>
                    <?php if (count($_items)): ?>
                        <ol id="cart-sidebar" class="mini-products-list">
                            <?php foreach ($_items as $_item): ?>
                                <?php echo $this->getItemHtml($_item) ?>
                            <?php endforeach; ?>
                        </ol>
                        <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
                    <?php else: ?>
                        <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
                    <?php endif ?>
                    <div class="top-subtotal"><?php echo $this->__('Subtotal') ?>: <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?></div>
                    <?php if ($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                        <div class="actions">
                            <?php echo $this->getChildHtml('extra_actions') ?>
                            <button type="button" title="<?php echo $this->__('Checkout') ?>" class="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
                        </div>
                    <?php endif ?>
                </div>
            </div>

    </div>
</div>
