<div class="imprint-page">
    <div class="col-md-6">
        <strong><?php echo Mage::getStoreConfig('general/imprint/company_first')?></strong><br/>
        <?php echo Mage::getStoreConfig('general/imprint/street')?><br/>
        <?php echo Mage::getStoreConfig('general/imprint/zip')?> 
            <?php echo Mage::getStoreConfig('general/imprint/city')?><br/>
        <?php echo Mage::getStoreConfig('general/imprint/country')?><br/><br/><br/>
        T: <?php echo Mage::getStoreConfig('general/imprint/telephone')?><br/>
        F: <?php echo Mage::getStoreConfig('general/imprint/fax')?><br/><br/>

        <a href="mailto:<?php echo Mage::getStoreConfig('general/imprint/email')?>"><?php echo Mage::getStoreConfig('general/imprint/email')?></a><br/>
        <br/>
        <?php echo Mage::getStoreConfig('general/imprint/court')?> - VAT-ID Nr. <?php echo Mage::getStoreConfig('general/imprint/vat_id')?> - 
        Geschäftsführer:  <?php echo Mage::getStoreConfig('general/imprint/ceo')?>
    </div>
    <div class="col-md-6">
        <h3>Copyrightvermerk</h3>
        <p>Alle Inhalte dieser Website - Text, Bild- und Bewegtbilddaten - sind urheberrechtlich geschützt. Bearbeitung, Nutzung und Vervielfältigung in jeder Form, einschließlich der Einbindung in fremde Internetauftritte, Datenbanksysteme etc. - ausschließlich mit schriftlicher Genehmigung der Rechteinhaber zulässig.</p>
    </div>
</div>

